atelectasis_concepts = [
    "Volume loss in affected lung region",
    "Crowding of pulmonary vessels",
    "Displacement of interlobar fissures",
    "Elevation of ipsilateral hemidiaphragm",
    "Shift of mediastinum toward the affected side",
    "Increased opacity in the collapsed lung zone",
    "Air bronchogram within area of collapse",
    "Compensatory overinflation of adjacent lung",
    "Crowded bronchovascular markings",
    "Blunting of costophrenic angle due to volume loss",
    "Loss of normal lung aeration",
    "Displacement of hilum toward the affected side",
    "Associated pleural thickening may be present",
    "Triangular or wedge-shaped opacity near lung periphery",
    "Silhouette sign obscuring heart or diaphragm border",
    "Obstruction of bronchus leading to collapse",
    "Reduced lung volume without consolidation",
    "Sharp demarcation between aerated and collapsed segments",
    "Unilateral hyperlucency of opposite lung",
    "Linear or band-like opacities indicating subsegmental collapse",
]

cardiomegaly_concepts = [
    "Enlarged cardiac silhouette",
    "Cardiothoracic ratio exceeds normal limits",
    "Prominent left heart border",
    "Rounding of the cardiac apex",
    "Displacement of the cardiac apex inferiorly and laterally",
    "Loss of waist of the left heart border",
    "Globular or boot-shaped heart appearance",
    "Double density sign indicating left atrial enlargement",
    "Elevation of the left main bronchus",
    "Widened mediastinum due to cardiac enlargement",
    "Splaying of the carina",
    "Obscured costophrenic angles from heart enlargement",
    "Increased transverse diameter of the heart",
    "Straightening of the left heart border",
    "Pulmonary vasculature congestion may be present",
    "Associated signs of heart failure may coexist",
    "Prominent pulmonary arteries",
    "Displacement of adjacent structures by enlarged heart",
    "Cardiac silhouette occupying more than 50% of thoracic width",
    "Generalized cardiomegaly affecting all chambers",
]

consolidation_concepts = [
    "Homogeneous increased lung opacity",
    "Air bronchograms visible within opacity",
    "Lobar or segmental distribution of opacity",
    "Silhouette sign present with obscured heart or diaphragm border",
    "Dense alveolar infiltrates in affected region",
    "Poorly defined margins of consolidation",
    "Opacity does not shift with patient position",
    "Confluent alveolar opacities in one lung zone",
    "No volume loss associated with opacity",
    "Opacity localized to a specific lung lobe",
    "Patchy consolidation seen in multiple segments",
    "No cavitation within consolidated area",
    "Uniform opacification suggesting alveolar filling",
    "Segmental airspace disease evident",
    "Consolidation abutting pleural surface",
    "Blurring of vascular markings within opacity",
    "Sharp demarcation between normal and affected lung",
    "Persistent opacity despite deep inspiration",
    "Consolidation causing silhouetting of adjacent structures",
    "Bronchial wall thickening adjacent to opacity",
]

edema_concepts = [
    "Bilateral perihilar opacities resembling bat-wing pattern",
    "Increased interstitial markings throughout lung fields",
    "Kerley B lines at lung bases",
    "Hazy vascular margins due to fluid overload",
    "Pleural effusion often seen bilaterally",
    "Diffuse alveolar infiltrates consistent with fluid accumulation",
    "Peribronchial cuffing indicating interstitial edema",
    "Cardiomegaly often present in cardiogenic edema",
    "Cephalization of pulmonary vasculature",
    "Fluffy, poorly marginated airspace opacities",
    "Symmetric lower lobe opacities",
    "Widened vascular pedicle suggesting fluid overload",
    "Obscuration of costophrenic angles due to fluid",
    "Rapid development of diffuse opacities",
    "Increased radiodensity in perihilar regions",
    "Engorged upper lobe veins on upright films",
    "Interlobular septal thickening visible",
    "Diffuse ground-glass appearance of lung fields",
    "Associated signs of heart failure commonly present",
    "Alveolar flooding without focal consolidation",
]

enlarged_cardiomediastinum_concepts = [
    "Widened mediastinal silhouette on frontal chest radiograph",
    "Prominent aortic knob indicating vascular enlargement",
    "Obscured contours of cardiac and mediastinal borders",
    "Displacement of trachea from midline",
    "Enlarged superior mediastinum visible",
    "Bulging of mediastinal contours into lung fields",
    "Double density sign suggesting left atrial enlargement",
    "Increased cardiomediastinal width",
    "Mediastinal opacity extending into upper zones",
    "Loss of normal mediastinal tapering",
    "Splaying of the carina due to mass effect",
    "Deviation of the esophagus or trachea",
    "Associated pleural effusions may be present",
    "Right paratracheal stripe widening",
    "Blurring of the aortopulmonary window",
    "Posterior mediastinal mass effect on lateral view",
    "Compression of adjacent lung tissue",
    "Enlargement involving multiple mediastinal compartments",
    "Evidence of lymphadenopathy or mediastinal masses",
    "Smooth or lobulated contour of widened mediastinum",
]

fracture_concepts = [
    "Discontinuity in cortical bone of the rib",
    "Sharp angulation of rib suggesting fracture",
    "Overlapping bone fragments indicating displaced fracture",
    "Linear lucency crossing rib shaft",
    "Fracture line visible without significant displacement",
    "Callus formation suggesting healing fracture",
    "Multiple rib fractures in posterior ribs",
    "Step-off deformity of rib margin",
    "Clavicular fracture with inferior displacement",
    "Widening of costochondral junction",
    "Compression deformity of thoracic vertebra",
    "Irregular bone contour at site of trauma",
    "Rib fractures with associated soft tissue swelling",
    "Segmental rib fractures indicating flail chest",
    "Old healed rib fracture with sclerosis",
    "Fracture associated with pneumothorax",
    "Non-displaced fracture of anterior rib arc",
    "Lucent line along scapular border indicating fracture",
    "Fracture fragment impinging on adjacent lung",
    "Fracture with periosteal reaction seen on follow-up imaging",
]

lung_lesion_concepts = [
    "Solitary pulmonary nodule with well-defined margins",
    "Irregular lung opacity suspicious for malignancy",
    "Spiculated mass in upper lobe",
    "Round opacity with lobulated contour",
    "Cavitary lesion with air-fluid level",
    "Calcified nodule in lung parenchyma",
    "Peripheral lung mass without associated consolidation",
    "Non-calcified nodule requiring further evaluation",
    "Well-circumscribed lesion adjacent to pleura",
    "Ill-defined opacity with surrounding ground-glass halo",
    "Multifocal lung lesions scattered across both lungs",
    "Mass effect causing distortion of adjacent structures",
    "Lung lesion with satellite nodules",
    "Lobulated mass with mediastinal extension",
    "Lesion obscuring adjacent vascular markings",
    "Increasing size of pulmonary lesion on serial imaging",
    "Central necrosis seen in larger lesion",
    "Subpleural opacity suggesting malignancy",
    "Asymmetric mass in one lung zone",
    "Pleural retraction adjacent to lung mass",
]

lung_opacity_concepts = [
    "Focal area of increased lung density",
    "Hazy opacity obscuring underlying structures",
    "Patchy airspace opacities in one or both lungs",
    "Diffuse bilateral lung opacities",
    "Non-specific ill-defined parenchymal density",
    "Confluent alveolar opacity in lower lobe",
    "Peripheral lung opacity with irregular margins",
    "Homogeneous opacity without volume loss",
    "Air bronchograms seen within opaque region",
    "Opacity with silhouetting of heart border",
    "Opacity not conforming to lobar distribution",
    "Reticulonodular opacities throughout lung fields",
    "Increased opacity adjacent to pleura",
    "Multifocal areas of parenchymal haziness",
    "Opacity consistent with interstitial thickening",
    "Unilateral dense consolidation-like opacity",
    "Opacity with associated volume loss",
    "Fluffy opacity pattern in perihilar region",
    "Nodular opacities coalescing into mass-like density",
    "Atypical opacity requiring differential diagnosis",
]

normal_concepts = [
    "Clear lung fields with no opacities",
    "Defined cardiac borders",
    "Sharp costophrenic angles",
    "Uniform vascular markings",
    "Normal mediastinal silhouette",
    "Absence of lymphadenopathy",
    "Normal bronchovascular markings",
    "No evidence of pleural thickening",
    "No abnormal lung parenchymal opacities",
    "Normal tracheobronchial tree",
    "Symmetrical diaphragmatic domes",
    "Clear hila",
    "Unremarkable soft tissues and bones",
    "No signs of pulmonary edema",
    "Absence of masses or nodules",
    "Normal aortic arch contour",
    "Lungs are well-aerated",
    "No evidence of pneumothorax",
    "Consistent radiographic density",
    "Regularly spaced rib intervals",
]

pleural_effusion_concepts = [
    "Blunting of the costophrenic angle",
    "Homogeneous opacity in lower lung zone",
    "Meniscus sign along lateral chest wall",
    "Increased density over lung base",
    "Obliteration of diaphragmatic contour",
    "Layering fluid seen on decubitus view",
    "Mass effect with mediastinal shift away from effusion",
    "Uniform opacity with smooth upper margin",
    "Air-fluid level suggesting hydropneumothorax",
    "Contralateral tracheal deviation with large effusion",
    "Fluid tracking into minor fissure",
    "Pleural capping at lung apex",
    "Effusion obscuring cardiac silhouette",
    "Elevated hemidiaphragm due to subpulmonic fluid",
    "Bilateral pleural effusions present",
    "Associated compressive atelectasis visible",
    "Rounded opacity in posterior costophrenic sulcus",
    "Pleural thickening with associated fluid collection",
    "Sharp demarcation between aerated lung and fluid",
    "Diffuse opacification consistent with large effusion",
]

pleural_other_concepts = [
    "Localized pleural thickening along lateral chest wall",
    "Calcified pleural plaques consistent with prior asbestos exposure",
    "Irregular pleural surface with nodular contours",
    "Diffuse pleural thickening with volume loss",
    "Apical pleural capping with fibrotic bands",
    "Pleural-based mass protruding into lung parenchyma",
    "Pleural calcification involving diaphragmatic surface",
    "Encasing pleural abnormality restricting lung expansion",
    "Unilateral pleural fibrosis with mediastinal shift",
    "Elevated hemidiaphragm with adjacent pleural scarring",
    "Linear opacity following pleural contour",
    "Thickened pleura causing distortion of lung edge",
    "Pleural mass with sharp inner margin",
    "Parietal pleural calcification visible on lateral view",
    "Smooth pleural thickening extending over multiple ribs",
    "Bilateral apical pleural thickening",
    "Pleural tethering resulting in architectural distortion",
    "Pleural-based lesion with no associated effusion",
    "Posterior pleural irregularity on lateral projection",
    "Thickened fissures indicating fibrotic pleural change",
]

pneumonia_concepts = [
    "Lobar consolidation with air bronchograms",
    "Patchy alveolar opacities in right lower lobe",
    "Unilateral focal opacity suggestive of infection",
    "Segmental consolidation without volume loss",
    "Peripheral ground-glass opacity indicating early pneumonia",
    "Dense airspace opacity in left upper lobe",
    "Multifocal areas of consolidation in both lungs",
    "Poorly defined patchy opacities consistent with infection",
    "Opacity obscuring right heart border (silhouette sign)",
    "Cavitary lesion within consolidated area",
    "Air bronchograms in area of lobar opacity",
    "Peribronchial thickening with surrounding infiltrates",
    "Ill-defined infiltrates extending to pleural surface",
    "Bilateral lower lobe opacities with inflammatory pattern",
    "Non-homogeneous opacity in middle lung zone",
    "Associated pleural effusion with adjacent consolidation",
    "Hazy airspace opacity without sharp margins",
    "Rapidly progressing airspace disease",
    "Opacity following anatomic lobar boundary",
    "Associated signs of infection such as fever and cough (clinically correlated)",
]

pneumothorax_concepts = [
    "Visible visceral pleural line with absent lung markings beyond",
    "Hyperlucent hemithorax without vascular markings",
    "Collapsed lung margin retracted toward hilum",
    "Deep sulcus sign seen on supine film",
    "Sharp delineation of lung edge against pleural air",
    "Increased radiolucency on affected side",
    "Air-filled pleural space with absent lung markings",
    "Shift of mediastinum in tension pneumothorax",
    "Flattened diaphragm on side of pneumothorax",
    "Compressed lung tissue adjacent to hilum",
    "Air outlining heart border in anterior pneumothorax",
    "Apical lucency with lung retraction",
    "Lack of vascular markings peripherally",
    "Tension pneumothorax with tracheal deviation",
    "No evidence of pleural effusion accompanying the air",
    "Asymmetric lung expansion after trauma",
    "Subtle apical lucency requiring careful inspection",
    "Deep costophrenic angle without lung markings",
    "Thin curvilinear line outlining collapsed lung",
    "Expiratory film shows enhanced visibility of pneumothorax",
]

concepts = (
    atelectasis_concepts
    + cardiomegaly_concepts
    + consolidation_concepts
    + edema_concepts
    + enlarged_cardiomediastinum_concepts
    + fracture_concepts
    + lung_lesion_concepts
    + lung_opacity_concepts
    + normal_concepts
    + pleural_effusion_concepts
    + pleural_other_concepts
    + pneumonia_concepts
    + pneumothorax_concepts
)
